# Generated by Django 5.2.4 on 2025-07-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenTech', '0002_event_eventregistration_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_type', models.CharField(choices=[('event_request', 'Event Creation Request'), ('general_inquiry', 'General Inquiry'), ('technical_support', 'Technical Support'), ('feedback', 'Feedback'), ('other', 'Other')], default='general_inquiry', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
