# Generated by Django 5.2.4 on 2025-07-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenTech', '0004_contact_event_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Count',
                'verbose_name_plural': 'Visitor Count',
            },
        ),
    ]
